function now(){return Date.now()}
export class TitanApprovalStore{
 constructor(state,{audit=()=>{}}={}){this.state=state;this.audit=audit;this.state.approvals=this.state.approvals||{}}
 create(request){const existing=Object.values(this.state.approvals).find(x=>x.status==="pending"&&x.type===request.type&&x.missionId===request.missionId&&x.packetId===request.packetId);if(existing)return existing;const id=request.id||`approval-${now()}-${Math.random().toString(36).slice(2,8)}`;const r={...request,id,status:"pending",approved:false,createdAt:now(),updatedAt:now()};this.state.approvals[id]=r;this.audit("approval-created",{id,type:r.type,missionId:r.missionId,packetId:r.packetId||null});return r}
 decide(id,{approved=false,actor="human",reason=null}={}){const r=this.state.approvals[id];if(!r)throw new Error("Unknown approval "+id);if(r.status!=="pending")throw new Error("Approval already decided");r.status=approved?"approved":"rejected";r.approved=!!approved;r.actor=actor;r.reason=reason;r.updatedAt=now();this.audit("approval-decided",{id,approved:!!approved,actor,reason});return r}
 findDecision(request){const sig=JSON.stringify([...(request.violations||[])].sort());return Object.values(this.state.approvals).find(x=>x.type===request.type&&x.missionId===request.missionId&&x.packetId===request.packetId&&JSON.stringify([...(x.violations||[])].sort())===sig&&["approved","rejected"].includes(x.status))||null}
 async request(request){return this.findDecision(request)||this.create(request)}
}
export function persistApprovedScopeExpansion({state,missionControl,audit=()=>{}}){return async ({request,approval,packet,builderId,changedPaths})=>{if(!approval?.approved)throw new Error("Scope expansion not approved");const missionId=packet?.mission?.id||packet?.mission_id||request?.missionId,m=missionControl.get(missionId);if(!m)throw new Error("Unknown mission "+missionId);const oldScope=[...(m.scopePaths||[])],extra=request?.violations||changedPaths||[];m.scopePaths=[...new Set([...oldScope,...extra])];m.updatedAt=Date.now();state.updatedAt=m.updatedAt;approval.oldScope=oldScope;approval.newScope=[...m.scopePaths];approval.persistedAt=Date.now();audit("scope-expansion-persisted",{missionId,builderId,approvalId:approval.id,oldScope,newScope:m.scopePaths,violations:request?.violations||[]});return m}}
