import {createWorkforceState} from "./state.js";
import {migrateWorkforceState} from "./migrations.js";
import {TitanWorkforceController} from "./controller.js";
import {TitanMissionControl} from "./mission-control.js";
import {TitanExecutionServices} from "./execution-services.js";
import {TitanCapabilityBroker} from "./capability-broker.js";
import {TitanMcpRegistry,installMcpService} from "./mcp-registry.js";
import {installExecutionCapabilities} from "./execution-capabilities.js";
import {TitanWorkforceIntegration} from "./integration.js";
import {installLegacyNativeBridge,installConversationServices,installStockNativeEventBridge} from "./native-bridge.js";
import {installStockServiceFallbacks} from "./stock-service-fallbacks.js";
import {createConversationService} from "./conversation-service.js";
import {TitanWorkforceControls} from "./controls.js";
import {TitanMergeController} from "./merge-controller.js";
import {installEngineeringCockpit} from "./cockpit.js";
import {TitanApprovalStore,persistApprovedScopeExpansion} from "./approvals.js";
import {createHighImpactAuthorizer} from "./high-impact-policy.js";
import {TitanCredentialBroker} from "./credential-broker.js";
import {TitanRuntimeVerifierRegistry,verifyMissionRuntime} from "./runtime-verifiers.js";
import {createAuthoritativeChangedPathResolver} from "./changed-path-evidence.js";
import {enforceScopedCodexBuildCapability} from "./scoped-codex-capability.js";
import {TitanLiveChatRuntime} from "./live-chat-runtime.js";
import {TitanArchitectureIndex} from "./architecture-index.js";
import {TitanRepositoryIntelligence} from "./repository-intelligence.js";
import {TitanMissionCompiler} from "./mission-compiler.js";
import {TitanContextCompiler} from "./context-compiler.js";

const KEY="titanDeveloperWorkforceV4";
async function load(){
 const LEGACY_KEY="titan5x5.state.v2";
 const stored=await chrome.storage.local.get([KEY,LEGACY_KEY]);
 const state=stored[KEY]?migrateWorkforceState(stored[KEY]):migrateWorkforceState(stored[LEGACY_KEY]||createWorkforceState());
 const audit=(type,data={})=>window.dispatchEvent(new CustomEvent("titan-workforce:audit",{detail:{type,data,at:Date.now()}}));
 const services=new TitanExecutionServices();
 const capabilities=new TitanCapabilityBroker({audit});
 const mcp=new TitanMcpRegistry({broker:capabilities,audit});
 installMcpService(services,mcp,audit);
 const controller=new TitanWorkforceController(state,{audit,services});
 const missions=new TitanMissionControl(state);
 const stopNativeEventBridge=installStockNativeEventBridge(services,audit);
 installLegacyNativeBridge(services,audit);
 const conversations=createConversationService();installConversationServices(services,{chat:conversations,work:conversations},audit);
 installStockServiceFallbacks(services,{registry:controller.registry,conversationService:conversations,audit});
 const executionCapabilities=installExecutionCapabilities({services,broker:capabilities,audit});
 executionCapabilities.sync();
 const approvals=new TitanApprovalStore(state,{audit});
 const credentials=new TitanCredentialBroker(state,{audit,approvalStore:approvals});
 const runtimeVerifiers=new TitanRuntimeVerifierRegistry({audit});
 capabilities.authorize=createHighImpactAuthorizer({approvalStore:approvals,audit});
 const installScopeGuard=()=>enforceScopedCodexBuildCapability(capabilities,{getChangedPaths:createAuthoritativeChangedPathResolver(capabilities,{audit}),audit,requestApproval:req=>approvals.request(req),persistScopeExpansion:persistApprovedScopeExpansion({state,missionControl:missions,audit})});
 installScopeGuard();
 const resyncCapabilities=()=>queueMicrotask(()=>{executionCapabilities.sync();installScopeGuard()});
 window.addEventListener("titan:stock-native-service",resyncCapabilities);
 const architecture=new TitanArchitectureIndex({audit});
 const repositoryIntelligence=new TitanRepositoryIntelligence({state,audit});
 const integration=new TitanWorkforceIntegration({state,controller,missionControl:missions,services,capabilities,repositoryIntelligence,architectureIndex:architecture,audit});
 integration.bindGlobals();
 const missionCompiler=new TitanMissionCompiler({profiles:integration.profileApi,audit});
 const contextCompiler=new TitanContextCompiler({profiles:integration.profileApi,contextProvider:(missionId,opts)=>integration.contextForMission(missionId,opts),provenance:integration.provenance,audit});
 const save=()=>chrome.storage.local.set({[KEY]:state});
 const liveChat=new TitanLiveChatRuntime({state,integration,missionControl:missions,services,audit,save});
 liveChat.start();
 const controls=new TitanWorkforceControls(controller,audit);const mergeController=new TitanMergeController({audit});
 const onMergeIndex=event=>{const d=event.detail||{};if(!d.repository||!d.nextCommit||!Array.isArray(d.changes))return;try{repositoryIntelligence.applyChanges({repository:d.repository,baseCommit:d.baseCommit,nextCommit:d.nextCommit,changes:d.changes});save().catch(()=>{})}catch(error){audit("repository-index-refresh-failed",{repository:d.repository,nextCommit:d.nextCommit,message:String(error?.message||error)})}};
 window.addEventListener("titan-workforce:merge-complete",onMergeIndex);
 const api={state,controller,missions,services,capabilities,mcp,approvals,credentials,runtimeVerifiers,verifyMissionRuntime:async missionId=>{const mission=missions.get(missionId);if(!mission)throw new Error("Unknown mission "+missionId);return verifyMissionRuntime(mission,{services,registry:runtimeVerifiers,audit})},executionCapabilities,integration,architecture,repositoryIntelligence,missionCompiler,contextCompiler,liveChat,controls,mergeController,stopNativeEventBridge,stopCapabilityResync:()=>window.removeEventListener("titan:stock-native-service",resyncCapabilities),stopRepositoryIndexRefresh:()=>window.removeEventListener("titan-workforce:merge-complete",onMergeIndex),save};
 globalThis.TitanCapabilityBroker=capabilities;
 globalThis.TitanMcpRegistry=mcp;
 globalThis.TitanDeveloperWorkforce=api;
 installEngineeringCockpit(api);
 await api.save();
 window.dispatchEvent(new CustomEvent("titan-workforce:ready",{detail:{schemaVersion:state.schemaVersion,readiness:integration.readiness()}}));
 return api;
}
load().catch(error=>{console.error("[Titan Workforce] bootstrap failed",error);window.dispatchEvent(new CustomEvent("titan-workforce:error",{detail:{message:String(error?.message||error)}}))});
