import {TitanAgentRegistry} from "./registry.js";
function control(a){return a.control||(a.control={paused:false,pauseReason:null,quarantined:false,quarantineReason:null,emergencyStopped:false,preEmergency:null})}
export class TitanWorkforceController{
 constructor(state,{audit=()=>{},services={},readinessGuard=null}={}){this.state=state;this.registry=new TitanAgentRegistry(state);this.audit=audit;this.services=services;this.readinessGuard=typeof readinessGuard==="function"?readinessGuard:null}
 setReadinessGuard(fn){this.readinessGuard=typeof fn==="function"?fn:null;return this}
 arm(){if(this.readinessGuard){const r=this.readinessGuard();if(!r?.ok){const e=new Error(r?.reason||"Workforce readiness verification failed");e.code="WORKFORCE_NOT_READY";e.readiness=r;throw e}}if(this.state.controls.emergencyStop)throw new Error("Cannot arm during emergency stop");if(this.state.controls.requiresReconciliation)throw new Error("Cannot arm before readiness/reconciliation");if(this.registry.list().some(a=>control(a).emergencyStopped))throw new Error("Cannot arm while agent emergency-stop flags remain");this.state.controls.armed=true;this.audit("workforce-armed",{});return true}
 disarm(reason="manual"){this.state.controls.armed=false;this.audit("workforce-disarmed",{reason});return true}
 emergencyStop(reason="manual"){this.state.controls.armed=false;this.state.controls.emergencyStop=true;this.state.controls.requiresReconciliation=true;this.state.controls.lastEmergencyAt=Date.now();for(const a of this.registry.list()){const c=control(a);if(!c.emergencyStopped)c.preEmergency={status:a.status,paused:c.paused,quarantined:c.quarantined,at:Date.now()};c.emergencyStopped=true}this.audit("workforce-emergency-stop",{reason,agents:this.registry.list().map(a=>a.id)});return true}
 clearEmergencyStop({reconciled=false}={}){if(!this.state.controls.emergencyStop)throw new Error("E-STOP is not active");this.state.controls.emergencyStop=false;this.state.controls.armed=false;this.state.controls.requiresReconciliation=!reconciled;for(const a of this.registry.list()){const c=control(a);c.emergencyStopped=false;if(c.preEmergency){c.paused=!!c.preEmergency.paused;c.quarantined=!!c.preEmergency.quarantined;c.preEmergency=null}}this.audit("workforce-emergency-cleared",{reconciled,armed:false});return true}
 markReconciled(evidence={}){if(this.state.controls.emergencyStop)throw new Error("Cannot reconcile while E-STOP active");this.state.controls.requiresReconciliation=false;this.audit("workforce-reconciled",{evidence});return true}
 assign(slotId,assignment){const s=this.registry.get(slotId);if(!s)throw new Error("Unknown agent slot "+slotId);const c=control(s);if(this.state.controls.emergencyStop||c.emergencyStopped||c.quarantined)throw new Error("Agent unavailable for assignment");const out=this.registry.assign(slotId,assignment);this.audit("agent-assigned",{slotId,missionId:out.missionId,profiles:out.profileIds});return out}
}
