const TERMINAL=new Set(["complete","verified","cancelled","superseded"]);
function ctrl(s){return s.control||(s.control={paused:false,pauseReason:null,quarantined:false,quarantineReason:null,emergencyStopped:false,preEmergency:null})}
export class TitanWorkforceControls{
 constructor(controller,audit=()=>{}){this.controller=controller;this.audit=audit}
 pauseAgent(id,reason="manual"){const s=this.controller.registry.get(id);if(!s)throw new Error("Unknown agent "+id);const c=ctrl(s);if(c.quarantined)throw new Error("Cannot pause quarantined agent");if(c.emergencyStopped||this.controller.state.controls.emergencyStop)throw new Error("Cannot pause during E-STOP");if(TERMINAL.has(s.status))return s;if(c.paused)return s;c.paused=true;c.pauseReason=reason;this.audit("agent-paused",{id,reason,status:s.status});return s}
 resumeAgent(id){const s=this.controller.registry.get(id);if(!s)throw new Error("Unknown agent "+id);const c=ctrl(s);if(c.quarantined)throw new Error("Cannot resume quarantined agent");if(c.emergencyStopped||this.controller.state.controls.emergencyStop)throw new Error("Cannot resume during E-STOP");if(!c.paused)throw new Error("Agent is not paused");if(TERMINAL.has(s.status))throw new Error("Cannot resume terminal agent");c.paused=false;c.pauseReason=null;this.audit("agent-resumed",{id,status:s.status});return s}
 quarantine(id,reason="manual"){const s=this.controller.registry.get(id);if(!s)throw new Error("Unknown agent "+id);const c=ctrl(s);c.quarantined=true;c.quarantineReason=reason;c.paused=false;c.pauseReason=null;this.audit("agent-quarantined",{id,reason,status:s.status});return s}
 unquarantine(id,{approved=false,reason="manual"}={}){const s=this.controller.registry.get(id);if(!s)throw new Error("Unknown agent "+id);const c=ctrl(s);if(!c.quarantined)throw new Error("Agent is not quarantined");if(!approved)throw new Error("Unquarantine requires explicit approval");if(this.controller.state.controls.emergencyStop||c.emergencyStopped)throw new Error("Cannot unquarantine during E-STOP");c.quarantined=false;c.quarantineReason=null;this.audit("agent-unquarantined",{id,reason,status:s.status,approved:true});return s}
 pauseSquad(squad,reason="manual"){return this.controller.registry.list().filter(s=>s.squad===squad&&!ctrl(s).quarantined&&!ctrl(s).emergencyStopped&&!TERMINAL.has(s.status)).map(s=>this.pauseAgent(s.id,reason))}
 resumeSquad(squad){return this.controller.registry.list().filter(s=>s.squad===squad&&ctrl(s).paused&&!ctrl(s).quarantined&&!ctrl(s).emergencyStopped&&!TERMINAL.has(s.status)).map(s=>this.resumeAgent(s.id))}
 effectiveState(id){const s=this.controller.registry.get(id);if(!s)return null;const c=ctrl(s);return c.emergencyStopped?"emergency-stopped":c.quarantined?"quarantined":c.paused?"paused":s.status}
}
