import assert from "node:assert/strict";
await import("../../titan-work-codex-pipeline.js");
const {TitanWorkCodexRuntime}=await import("./work-codex-runtime.js");
const {TitanGitMissionSubstrate}=await import("./git-mission-substrate.js");
const {createWorkforceState}=await import("./state.js");
const {TitanMissionControl}=await import("./mission-control.js");
const {TitanWorkforceController,validateAssignmentInvariants}=await import("./controller.js");
const pipeline=globalThis.TitanWorkCodexPipeline;
const state=createWorkforceState(),missionControl=new TitanMissionControl(state),controller=new TitanWorkforceController(state,{missionControl});
missionControl.upsert({id:"mission-1",title:"Implement bounded change",goal:"Change one scoped file",repository:"Masterleeaus/example",branch:"issue-1/test",scope_paths:["src/**"],constraints:["preserve architecture"],acceptance:[{id:"ac-1",text:"done",done:true}],verificationRequirements:[],dependencies:[]});
controller.assignMission("mission-1","SUPERVISOR_A",{expectedExecutionClass:"work_supervisor"});
const mission=missionControl.get("mission-1");mission.acceptanceCriteria=[{id:"ac-1",text:"done",done:true}];mission.scopePaths=["src/**"];mission.runtimeRequirements=[];
const calls={work:0,build:0,orchestrate:0},workResult={next_decision:"READY_FOR_CODEX",approved_findings:["finding"],approved_delta:{required_changes:["edit scoped implementation"],scope_paths:["src/**"],expected_files:["src/feature.js"],tests:[{name:"unit",passed:true,status:"passed"}]}};
const integration={controller,normalizePipelineMission:m=>({id:m.id,title:m.title,goal:m.goal,repository:m.repository,branch:m.branch,constraints:m.constraints||[],acceptance_criteria:m.acceptanceCriteria||[],runtime_requirements:m.runtimeRequirements||[],metadata:{}}),async requestWorkReview(_squad,request){calls.work++;return{parsed:workResult}},async dispatchCodexPacket(builderId,packet){calls.build++;return{files_changed:["src/feature.js"],diff:"diff --git a/src/feature.js b/src/feature.js",tests:[{name:"unit",passed:true,status:"passed"}],commit:{sha:"abc"},branch:{name:"issue-1/test"},pr:{number:1,url:"https://example.invalid/pr/1"},ci:{passed:true},blockers:[],remaining_implementation:[]}},async orchestrate(){calls.orchestrate++;return{decision:"COMPLETE",reason:"mock orchestrator"}}};
const githubTruth={commitExists:true,ciPassed:true,merged:true,presentOnMain:true,mergeCommit:"merge123",headSha:"abc"};
const services={get(kind){if(kind==="codex")return{build(){},orchestrate(){}};if(kind==="github")return{verify:async()=>githubTruth};return null}};
const capabilities={has:name=>["codex.build","codex.orchestrate"].includes(name)};
const gitSubstrate=new TitanGitMissionSubstrate(state);gitSubstrate.acquire({missionId:mission.id,builderId:"BUILDER_A",branch:mission.branch,worktree:"/tmp/mission-1",scopePaths:mission.scopePaths});
const runtime=new TitanWorkCodexRuntime({state,integration,missionControl,services,capabilities,gitSubstrate,pipelineApi:pipeline});
const event={type:"supervisor_review_required",workerId:"A1",squad:"A",missionId:mission.id,cycleId:"cycle-1",detail:{completedPasses:[1,2,3,4,5].map(passNumber=>({passNumber,result:{text:"pass "+passNumber}}))}};
const request=pipeline.adaptChatSupervisorReviewEvent(event,integration.normalizePipelineMission(mission));
const result=await runtime.handleSupervisorBoundary({event,request,supervisorId:"SUPERVISOR_A",squad:"A"});
assert.equal(result.decision.state,"COMPLETE");assert.equal(mission.status,"complete");assert.equal(calls.work,1);assert.equal(calls.build,1);assert.equal(calls.orchestrate,1);assert(validateAssignmentInvariants(state).ok);
assert.equal(gitSubstrate.get(mission.id).status,"merged");
console.log("Native Work → Codex → Orchestrator current-main acceptance PASS");
