import {TitanCapabilityBroker} from "./capability-broker.js";import {createWorkforceState} from "./state.js";import {TitanMissionControl} from "./mission-control.js";import {TitanApprovalStore,persistApprovedScopeExpansion} from "./approvals.js";import {createAuthoritativeChangedPathResolver} from "./changed-path-evidence.js";import {enforceScopedCodexBuildCapability} from "./scoped-codex-capability.js";
const assert=(x,m)=>{if(!x)throw new Error(m)};const state=createWorkforceState(),missions=new TitanMissionControl(state);missions.upsert({id:"m1",title:"scope",scope_paths:["src/**"]});const broker=new TitanCapabilityBroker();let paths=["src/a.js"],rawCalls=0;
broker.register("repo.diff",async()=>({files:paths}),{classification:"READ"});broker.register("codex.build",async()=>{rawCalls++;return {commit:"c1"}},{classification:"WRITE",source:"native"});
const approvals=new TitanApprovalStore(state);const options={getChangedPaths:createAuthoritativeChangedPathResolver(broker),requestApproval:r=>approvals.request(r),persistScopeExpansion:persistApprovedScopeExpansion({state,missionControl:missions})};enforceScopedCodexBuildCapability(broker,options);
const ctx={allowedCapabilities:["codex.build","repo.diff"]};let r=await broker.call("codex.build",{builderId:"BUILDER_A",packet:{id:"p1",mission_id:"m1",scope_paths:["src/**"]}},ctx);assert(r.scopeVerification.ok,"in-scope failed");
paths=["src/a.js","secret/x.js"];let pending=false,id;try{await broker.call("codex.build",{builderId:"BUILDER_A",packet:{id:"p2",mission_id:"m1",scope_paths:["src/**"]}},ctx)}catch(e){pending=e.code==="SCOPE_APPROVAL_PENDING";id=e.approvalId}assert(pending&&id,"violation did not stop");approvals.decide(id,{approved:true,actor:"test"});
r=await broker.call("codex.build",{builderId:"BUILDER_A",packet:{id:"p2",mission_id:"m1",scope_paths:["src/**"]}},ctx);assert(r.scopeVerification.ok&&r.scopeExpansion,"approved expansion failed");assert(missions.get("m1").scopePaths.includes("secret/x.js"),"scope not persisted");
broker.register("codex.build",async()=>({commit:"raw2"}),{classification:"WRITE",source:"native-resync"});enforceScopedCodexBuildCapability(broker,options);assert(broker.get("codex.build").metadata.scopeLocked===true,"resync bypassed scope guard");
console.log("Scoped Codex capability enforcement PASS",rawCalls);
